### ISSUE TITLE
New user question.

### ISSUE THREAD

**Issue by FenrisWolffe** [SuperGouge/HearthheadCollectionManager#1]
I have Hearthstone Deck Tracker, and the Collection Manager.. how do I use this script?

**Comment by SuperGouge** [comment]
Since the developer of the plugin doesn't seem to want to accept my pull request you can download the compiled release of this fork [here](https://github.com/SuperGouge/Hearthstone-Collection-Tracker/releases/tag/0.2).
After that, just use the import and export buttons from Hearthhead and the plugin, depending on what you want to do (e.g. "Export" on Hearthhead, copy to clipboard, then "Import from Clipboard" in plugin).

**Comment by FenrisWolffe** [comment]
I see no export collection on Hearthhead. Perhaps screenshots or instructions?

**Comment by SuperGouge** [comment]
You should be able to see those two buttons below the hero bars:
![Hearthhead collection buttons](https://cloud.githubusercontent.com/assets/3006175/8019761/1dd31228-0c5f-11e5-8d6e-d4d60a1afa80.png)

If you can't see them, either update the script to 1.0.1 or make sure you are on the english version of the site (http://www.hearthhead.com/collection).

**Comment by FenrisWolffe** [comment]
I asked above how to use/install the script.

**Comment by FenrisWolffe** [comment]
Ok. Just figured out greasemonkey, etc.

**Comment by SuperGouge** [comment]
Yes you need a user script manager for this (Greasemonkey, Tampermonkey, Scriptish, etc.)

**Comment by FenrisWolffe** [comment]
Took me hours, so instructions for newbies would have been nice. :)

**Comment by SuperGouge** [comment]
That's why I added installation instructions in the readme.
